version: '3.8'

services:
  # 1. FRONTEND
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: chat-frontend
    restart: "no"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000

  # 2. BACKEND
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat-backend
    restart: "no"
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - MONGOURL=${MONGOURL}
      - SECRET=${SECRET}
      - APP_PASSWORD=${APP_PASSWORD}
      - AI_USER_PASSWORD=${AI_USER_PASSWORD}
      - AI_API_URL=${AI_API_URL}
      - AI_API_KEY=${AI_API_KEY}
    depends_on:
      - mongodb

  # 3. DATABASE
  mongodb:
    image: mongo:4.4
    container_name: chat-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  #4. Ollama
  ollama:
    image: ollama/ollama:0.17.0
    container_name: chat-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  mongo-data:
    driver: local
  ollama-data:
    driver: local
